service: cvs-technical-records-v3

provider:
  name: aws
  runtime: nodejs22.x
  stage: dev
  timeout: 60
  region: eu-west-1
  environment:
    BRANCH: local
    DDB_OFFLINE_ENDPOINT: http://localhost:8000
    AWS_ACCESS_KEY_ID: accessKeyId
    AWS_SECRET_ACCESS_KEY: secretAccessKey
    
resources:
  Resources:
    testNumber:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cvs-${self:provider.environment.BRANCH}-flat-tech-records
        AttributeDefinitions:
          - AttributeName: createdTimestamp
            AttributeType: "S"
          - AttributeName: trailerId
            AttributeType: "S"
          - AttributeName: partialVin
            AttributeType: "S"
          - AttributeName: primaryVrm
            AttributeType: "S"
          - AttributeName: vin
            AttributeType: "S"
          - AttributeName: systemNumber
            AttributeType: "S"
        KeySchema:
          - AttributeName: systemNumber
            KeyType: HASH
          - AttributeName: createdTimestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 0
          WriteCapacityUnits: 0
        GlobalSecondaryIndexes:
          - IndexName: PartialVinIndex
            KeySchema:
              - AttributeName: partialVin
                KeyType: HASH
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes: 
                - techRecord_createdByName
                - techRecord_chassisModel
                - techRecord_make
                - trailerId
                - techRecord_chassisMake
                - techRecord_reasonForCreation
                - techRecord_manufactureYear
                - primaryVrm
                - vin
                - techRecord_statusCode
                - createdTimestamp
                - techRecord_vehicleType
                - systemNumber
                - techRecord_model
            ProvisionedThroughput:
              ReadCapacityUnits: 0
              WriteCapacityUnits: 0

          - IndexName: SysNumIndex
            KeySchema:
              - AttributeName: systemNumber
                KeyType: HASH
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes: 
                - techRecord_createdByName
                - techRecord_chassisModel
                - techRecord_make
                - trailerId
                - techRecord_chassisMake
                - techRecord_reasonForCreation
                - techRecord_manufactureYear
                - primaryVrm
                - vin
                - techRecord_statusCode
                - createdTimestamp
                - techRecord_vehicleType
                - systemNumber
                - techRecord_model
            ProvisionedThroughput:
              ReadCapacityUnits: 0
              WriteCapacityUnits: 0

          - IndexName: TrailerIdIndex
            KeySchema:
              - AttributeName: trailerId
                KeyType: HASH
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes: 
                - techRecord_createdByName
                - techRecord_chassisModel
                - techRecord_make
                - trailerId
                - techRecord_chassisMake
                - techRecord_reasonForCreation
                - techRecord_manufactureYear
                - primaryVrm
                - vin
                - techRecord_statusCode
                - createdTimestamp
                - techRecord_vehicleType
                - systemNumber
                - techRecord_model
            ProvisionedThroughput:
              ReadCapacityUnits: 0
              WriteCapacityUnits: 0

          - IndexName: VRMIndex
            KeySchema:
              - AttributeName: primaryVrm
                KeyType: HASH
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes: 
                - techRecord_createdByName
                - techRecord_chassisModel
                - techRecord_make
                - trailerId
                - techRecord_chassisMake
                - techRecord_reasonForCreation
                - techRecord_manufactureYear
                - primaryVrm
                - vin
                - techRecord_statusCode
                - createdTimestamp
                - techRecord_vehicleType
                - systemNumber
                - techRecord_model
            ProvisionedThroughput:
              ReadCapacityUnits: 0
              WriteCapacityUnits: 0

          - IndexName: VinIndex
            KeySchema:
              - AttributeName: vin
                KeyType: HASH
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes: 
                - techRecord_createdByName
                - techRecord_chassisModel
                - techRecord_make
                - trailerId
                - techRecord_chassisMake
                - techRecord_reasonForCreation
                - techRecord_manufactureYear
                - primaryVrm
                - vin
                - techRecord_statusCode
                - createdTimestamp
                - techRecord_vehicleType
                - systemNumber
                - techRecord_model
            ProvisionedThroughput:
              ReadCapacityUnits: 0
              WriteCapacityUnits: 0

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      dev:
        sources:
          - table: cvs-${self:provider.environment.BRANCH}-flat-tech-records
            sources: [./tests/resources/technical-records-v3.json]

plugins:
  - serverless-dotenv-plugin
  - serverless-dynamodb
  - serverless-offline
