AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
    SearchLambdaFunction:
      Type: 'AWS::Serverless::Function'
      Properties:
        CodeUri: src/handler/
        Handler: search.handler
        Runtime: nodejs18.x
        Events:
          SearchLambdaApi:
            Type: Api
            Properties:
              Path: /v3/technical-records/search/{searchIdentifier}
              Method: get
    GetLambdaFunction:
      Type: 'AWS::Serverless::Function'
      Properties:
        CodeUri: src/handler/
        Handler: get.handler
        Runtime: nodejs18.x
        Events:
          GetLambdaApi:
            Type: Api
            Properties:
              Path: /v3/technical-records/{systemNumber}/{createdTimestamp}
              Method: get
    PostLambdaFunction:
      Type: 'AWS::Serverless::Function'
      Properties:
        CodeUri: src/handler/
        Handler: post.handler
        Runtime: nodejs18.x
        Events:
          PostLambdaApi:
            Type: Api
            Properties:
              Path: /v3/technical-records
              Method: post
    UpdateLambdaFunction:
      Type: 'AWS::Serverless::Function'
      Properties:
        CodeUri: src/handler/
        Handler: update.handler
        Runtime: nodejs18.x
        Timeout: 20
        Events:
          UpdateLambda:
            Type: Api
            Properties:
              Path: /v3/technical-records/{systemNumber}/{createdTimestamp}
              Method: post
