AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
    SearchLambdaFunction:
      Type: 'AWS::Serverless::Function'
      Properties:
        CodeUri: src/handler/
        Handler: search.handler
        Runtime: nodejs18.x
        Events:
          SearchLambdaApi:
            Type: Api
            Properties:
              Path: /
              Method: get

Outputs:
  SearchLambdaApi:
    Description: "API Gateway endpoint URL for SearchLambdaFunction on dev stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/"
  SearchLambdaFunction:
    Description: "Search Lambda Function ARN"
    Value: !GetAtt GetLambdaFunction.Arn
