name: Build hash and deploy to S3
run-name: "${{ github.actor }} - ${{ github.ref_name }} - ${{ github.run_id }} 🚀"

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/CB2-10412'

jobs:
  Extract_Services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: extraction
        run: |
          SERVICES_LIST=$(yq eval '.Resources | keys | .[] | select(. != "LocalQueue")' template.yml)
          echo -e "SERVICES_LIST: \n$SERVICES_LIST"

      - uses: actions/github-script@v6
        id: script
        with:
          script: |
            import { LAMBDA_NAMES } from "./webpack/webpack.production.js";
            LAMBDA_NAMES.map(item => console.log(item))
          result-encoding: string


#  Build:
#    uses: dvsa/cvs-github-actions/.github/workflows/build-node-hash-monorepo.yaml@feature/CB2-10412
#    with:
#      services: [service1, service2]
#    secrets:
#      CVS_MGMT_AWS_ROLE: ${{ secrets.CVS_MGMT_AWS_ROLE }}
#      DVSA_AWS_REGION: ${{ secrets.DVSA_AWS_REGION }}


#        "cvs-svc-technical-records-v3" : [
#          'ArchiveLambdaFunction',
#          'UnarchiveLambdaFunction',
#          'SearchLambdaFunction',
#          'GetLambdaFunction',
#          'PatchLambdaFunction',
#          'PostLambdaFunction',
#          'PromoteLambdaFunction',
#          'UpdateVrmFunction',
#          'GeneratePlateFunction',
#          'GenerateLetterFunction',
#          'SyncTestResultInfoFunction',
#          'UpdateVinFunction'
