name: Build hash and deploy to S3
run-name: "${{ github.actor }} - ${{ github.ref_name }} - ${{ github.run_id }} 🚀"

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/CB2-10412'

jobs:
  Build_Hash:
    uses: dvsa/cvs-github-actions/.github/workflows/build-node-hash-monorepo.yaml@feature/CB2-10412
    with:
      mono_repo: true
    secrets:
      CVS_MGMT_AWS_ROLE: ${{ secrets.CVS_MGMT_AWS_ROLE }}
      DVSA_AWS_REGION: ${{ secrets.DVSA_AWS_REGION }}
