name: Build hash and deploy to S3
run-name: "${{ github.actor }} - ${{ github.ref_name }} - ${{ github.run_id }} 🚀"

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/CB2-10412'

jobs:
  Extract_Services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: extract services (YAML)
        run: |
          SERVICES_LIST=$(yq eval '.Resources | keys | .[] | select(. != "LocalQueue")' template.yml)
          echo -e "SERVICES_LIST: \n$SERVICES_LIST"

#      - name: Setup Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version-file: '.nvmrc'
#
#      - name: Install dependencies
#        run: npm ci

      - name: Extract services (javascript)
        uses: actions/github-script@v7
        with:
          script: |
            module.exports = { lambdaNames: LAMBDA_NAMES }
            const { lambdaNames } = require('./webpack/webpack.production.js')
          result-encoding: string


#  Build:
#    uses: dvsa/cvs-github-actions/.github/workflows/build-node-hash-monorepo.yaml@feature/CB2-10412
#    with:
#      services: [service1, service2]
#    secrets:
#      CVS_MGMT_AWS_ROLE: ${{ secrets.CVS_MGMT_AWS_ROLE }}
#      DVSA_AWS_REGION: ${{ secrets.DVSA_AWS_REGION }}


#        "cvs-svc-technical-records-v3" : [
#          'ArchiveLambdaFunction',
#          'UnarchiveLambdaFunction',
#          'SearchLambdaFunction',
#          'GetLambdaFunction',
#          'PatchLambdaFunction',
#          'PostLambdaFunction',
#          'PromoteLambdaFunction',
#          'UpdateVrmFunction',
#          'GeneratePlateFunction',
#          'GenerateLetterFunction',
#          'SyncTestResultInfoFunction',
#          'UpdateVinFunction'
