name: CI

on: 
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      local-dynamodb:
        image: amazon/dynamodb-local
        ports:
          - '8000:8000'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      # - name: Run lint
      #   run: npm run lint:ci
      # - name: Run tests
      #   run: npm run test:ci
      # - name: Build
      #   run: npm run build:prod
      - name: Setup dotenv
        run: cp .env.example .env
      - name: Replace docker network
        run: |
          echo "$(docker network ls | grep github_network | awk '{print $2}')"
          # sed -i "s/dynamo/$(docker network ls | grep github_network | awk '{print $2}')/" .env
          sed -i "s/dynamo/0.0.0.0/" .env
          cat .env
      - name: Start ci
        run: npm run test-i
        env:
          AWS_ACCESS_KEY_ID: foo
          AWS_SECRET_ACCESS_KEY: bar
        continue-on-error: true
      - name: Debug containers
        run: |
          docker ps
          docker network ls
          echo "####################################"
          docker network inspect $(docker network ls | grep github_network | awk '{print $2}') 


